sudo: required
services:
  - docker

before_install:
  - docker build -t vikramnagarkar/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vikramnagarkar/client-test npm test -- --coverage

after_success:
  - docker build -t vikramnagarkar/multi-client ./client
  - docker build -t vikramnagarkar/multi-nginx ./nginx
  - docker build -t vikramnagarkar/multi-server ./server
  - docker build -t vikramnagarkar/multi-worker ./worker

# Login to docker hub
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vikramnagarkar/multi-client
  - docker push vikramnagarkar/multi-nginx
  - docker push vikramnagarkar/multi-server
  - docker push vikramnagarkar/multi-worker

# take the above images and push them to docker hub

