apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
specs:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
      specs:
        containers:
          - name: client
            image: vikramnagarkar/multi-client
            ports:
              - containerPort: 3000
